### ISSUE TITLE
Bruno's trackpad

### ISSUE THREAD

**Issue by deeawolff** [Greenyexe/egg#2]

**Comment by Zoobdude** [comment]
I see, will be looking into it shortly. Will escalate this to the devs

**Comment by Zoobdude** [comment]
The devs are having difficulty. They say they can't fix it as every time they look at it, they shoot themselves in the foot. I am afraid that this will have to be re-opened for now

**Comment by Zoobdude** [comment]
as you can see, I have assigned the def

**Comment by Zoobdude** [comment]
v

**Comment by BrunoGreenfield** [comment]
I have been working

**Comment by Zoobdude** [comment]
I'll burn it shortly

**Comment by BrunoGreenfield** [comment]
I personally see nothing wrong with it. Seems like a re-boot fixed it :)

**Comment by Zoobdude** [comment]
I'll sure be booting it.
